<?php

namespace AppBundle\Repository;

/**
 * DomaineRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DomaineRepository extends \Doctrine\ORM\EntityRepository
{
    public function liste()
    {
        return $this->createQueryBuilder('d')->orderBy('d.libelle','ASC');
    }

    /**
     * Nombre de domaine disponible
     */
    public function getNombreDomaine()
    {
        return $this->createQueryBuilder('d')->select('count(d.id)')->getQuery()->getSingleScalarResult();
    }
}
