<?php

namespace AppBundle\Repository;

/**
 * FactureRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FactureRepository extends \Doctrine\ORM\EntityRepository
{
    public function getNombreFactrure()
    {
        return $this->createQueryBuilder('f')
                    ->select('count(f.id)')
                    ->getQuery()->getSingleScalarResult()
            ;
    }

    public function findFacture($reference)
    {
        return $this->createQueryBuilder('f')
                    ->where('f.id = :reference')
                    ->setParameter('reference', $reference)
            ;
    }
}
