<?php

namespace AppBundle\Repository;

use Doctrine\ORM\NoResultException;

/**
 * FournisseurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FournisseurRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * Generation du code du fournisseur
     */
    public function getCodeFournisseur()
    {
        // Recherche du nombre de fournisseur
        $compteur = $this->createQueryBuilder('f')->select('count(f.id)')->getQuery()->getSingleScalarResult();

        // Si le compteur est different de 0 alors recuperer le dernier id
        // Sinon affecter le code initial
        if ($compteur != 0){
            $q = $this->createQueryBuilder('f')->select('f.id')->orderBy('f.id', 'DESC')->setMaxResults('1');
            try{
                $qb = $q->getQuery()->getSingleScalarResult();
                // Incrementé de +1 l'id puis affecter sur 4 positions
                $id = $qb + 1;
                if ($id < 10){ return 'F00'.$id; }
                elseif ($id < 100){ return 'F0'.$id; }
                else{ return 'F'.$id; }
            }catch (NoResultException $e){
                return $e;
            }
        }else{
            return $code ='F001';
        }
    }

}
