<?php

namespace AppBundle\Repository;

/**
 * InventorierRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InventorierRepository extends \Doctrine\ORM\EntityRepository
{
}
