<?php

namespace AppBundle\Repository;

/**
 * ProduitRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProduitRepository extends \Doctrine\ORM\EntityRepository
{
    public function liste()
    {
        return $this->createQueryBuilder('p')->orderBy('p.libelle', 'ASC');
    }

    public function findByReferenceOrCode($reference)
    {
        $q = $this->createQueryBuilder('p')
                    ->where('p.reference = :reference')
                    ->orWhere('p.codebarre = :reference')
                    ->setParameter('reference', $reference)
            ;
        if ($q->getQuery()->getResult()){
            return $q->getQuery()->getSingleResult();
        }else{
            return false;
        }
    }

    /**
     * @param null $codeBarre
     * @return array|bool
     */
    public function findByCodeBarre($codeBarre = null)
    {
        if ($codeBarre){
            return $this->createQueryBuilder('p')
                        ->where('p.codebarre = :code')
                        ->setParameter('code', $codeBarre)
                        ->getQuery()->getResult();
        }else{
            return false;
        }
    }

    /**
     * @return array
     */
    public function findByReferenceIsNull()
    {
        return $this->createQueryBuilder('p')
                    ->where('p.reference IS NULL')
                    ->getQuery()->getResult()
            ;
    }
}
